# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nearsdksample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nearsdksample
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport'
    # Add any other subspecs you want to use in your project
  ]
  
  pod 'RNNearIt', :path => '../node_modules/react-native-nearit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end