# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nearsdksample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nearsdksample
  pod 'NearITSDK', '2.2.1'

end
